import express from 'express';
import pg from 'pg';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const {Pool}=pg;
const app=express();
const PORT=Number(process.env.PORT||3000);
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:false,max:10});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
const q=(text,params=[])=>pool.query(text,params);
const uuid=()=>crypto.randomUUID();
const b64url=b=>Buffer.from(b).toString('base64url');
const fromB64url=s=>Buffer.from(String(s),'base64url');
const digest=s=>crypto.createHash('sha256').update(String(s)).digest('hex');
const newSalt=()=>b64url(crypto.randomBytes(16));
const hashSecret=(value,salt,iterations)=>b64url(crypto.pbkdf2Sync(String(value),fromB64url(salt),iterations,32,'sha256'));
const hashPin=(v,s)=>hashSecret(v,s,210000);
const hashAdmin=(v,s)=>hashSecret(v,s,240000);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));

app.set('trust proxy',1);
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:true}));
app.use(cookieParser());

async function ensureSchema(){
 const sql=[
  `CREATE SEQUENCE IF NOT EXISTS el_enrollment_seq START 1`,
  `CREATE SEQUENCE IF NOT EXISTS el_request_seq START 1`,
  `CREATE TABLE IF NOT EXISTS student_accounts(id uuid PRIMARY KEY,username text UNIQUE NOT NULL,full_name text NOT NULL,pin_salt text NOT NULL,pin_hash text NOT NULL,language text NOT NULL DEFAULT 'English',enrollment_id text UNIQUE NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),last_login_at timestamptz,profile_course text,profile_institution text,photo_data bytea,photo_mime text)`,
  `CREATE TABLE IF NOT EXISTS student_sessions(token_hash text PRIMARY KEY,account_id uuid NOT NULL REFERENCES student_accounts(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS learning_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),request_id text UNIQUE NOT NULL,user_id uuid NOT NULL REFERENCES student_accounts(id) ON DELETE CASCADE,student_name text,enrollment_id text,university text NOT NULL,programme text NOT NULL,semester text NOT NULL,subject text NOT NULL,chapter text NOT NULL,materials jsonb NOT NULL DEFAULT '[]'::jsonb,notes text,status text NOT NULL DEFAULT 'Under review',price numeric,delivery_text text,payment_ref text,payment_status text NOT NULL DEFAULT 'Pending',access_granted boolean NOT NULL DEFAULT false,progress integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS learning_materials(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),request_id text NOT NULL,title text NOT NULL,kind text NOT NULL,url text NOT NULL,description text,created_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS contact_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,email text NOT NULL,message text NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS sla_admin_security(id integer PRIMARY KEY,code_salt text,code_hash text,setup_token_hash text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
  `INSERT INTO sla_admin_security(id) VALUES(1) ON CONFLICT(id) DO NOTHING`,
  `CREATE TABLE IF NOT EXISTS sla_admin_sessions(token_hash text PRIMARY KEY,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS student_notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),account_id uuid NOT NULL REFERENCES student_accounts(id) ON DELETE CASCADE,title text NOT NULL,message text NOT NULL,type text NOT NULL DEFAULT 'info',is_read boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS student_thoughts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),account_id uuid NOT NULL REFERENCES student_accounts(id) ON DELETE CASCADE,student_name text NOT NULL,course text NOT NULL,thought text NOT NULL,approved boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE INDEX IF NOT EXISTS learning_requests_user_idx ON learning_requests(user_id,created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS notifications_user_idx ON student_notifications(account_id,created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS materials_request_idx ON learning_materials(request_id,created_at DESC)`
 ];
 for(const s of sql) await q(s);
 await q(`DELETE FROM student_sessions WHERE expires_at<now()`);
 await q(`DELETE FROM sla_admin_sessions WHERE expires_at<now()`);
}

async function createStudentSession(res,accountId){
 const raw=b64url(crypto.randomBytes(32)),h=digest(raw);
 await q(`DELETE FROM student_sessions WHERE account_id=$1 OR expires_at<now()`,[accountId]);
 await q(`INSERT INTO student_sessions(token_hash,account_id,expires_at) VALUES($1,$2,now()+interval '30 days')`,[h,accountId]);
 res.cookie('el_session',raw,{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:30*86400000});
}
async function student(req){
 const raw=req.cookies?.el_session;if(!raw)return null;
 const r=await q(`SELECT a.id,a.username,a.full_name,a.language,a.enrollment_id,a.profile_course,a.profile_institution,a.created_at,CASE WHEN a.photo_data IS NULL THEN NULL ELSE '/api/student/photo' END AS photo_url FROM student_sessions s JOIN student_accounts a ON a.id=s.account_id WHERE s.token_hash=$1 AND s.expires_at>now()`,[digest(raw)]);
 return r.rows[0]||null;
}
async function requireStudent(req,res){const a=await student(req);if(!a){res.status(401).json({error:'Please log in.'});return null;}return a;}
async function clearStudent(req,res){const raw=req.cookies?.el_session;if(raw)await q(`DELETE FROM student_sessions WHERE token_hash=$1`,[digest(raw)]);res.clearCookie('el_session',{path:'/'});}
async function createAdminSession(res){const raw=b64url(crypto.randomBytes(32));await q(`DELETE FROM sla_admin_sessions WHERE expires_at<now()`);await q(`INSERT INTO sla_admin_sessions(token_hash,expires_at) VALUES($1,now()+interval '12 hours')`,[digest(raw)]);res.cookie('sla_admin_session',raw,{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:12*3600000});}
async function adminState(req){const c=await q(`SELECT code_hash IS NOT NULL AS configured FROM sla_admin_security WHERE id=1`);const configured=!!c.rows[0]?.configured;const raw=req.cookies?.sla_admin_session;if(!raw)return{configured,authenticated:false};const s=await q(`SELECT 1 FROM sla_admin_sessions WHERE token_hash=$1 AND expires_at>now()`,[digest(raw)]);return{configured,authenticated:!!s.rows.length};}
async function requireAdmin(req,res){const s=await adminState(req);if(!s.authenticated){res.status(401).json({error:'Admin access code required.'});return false;}return true;}
async function notify(accountId,title,message,type='info'){await q(`INSERT INTO student_notifications(account_id,title,message,type) VALUES($1,$2,$3,$4)`,[accountId,title,message,type]);}

app.get('/health',(req,res)=>res.json({ok:true,service:'SELFISH LEARNING ACADEMY'}));

app.post('/api/student/register',async(req,res,next)=>{try{
 const b=req.body||{},fullName=String(b.fullName||'').trim().slice(0,100),username=String(b.username||'').trim().toLowerCase(),pin=String(b.pin||''),language=['English','Malayalam','Arabic'].includes(String(b.language))?String(b.language):'English';
 if(fullName.length<2)return res.status(400).json({error:'Enter your full name.'});
 if(!/^[a-z0-9_.-]{3,30}$/.test(username))return res.status(400).json({error:'Username must be 3–30 characters using letters, numbers, dot, underscore or hyphen.'});
 if(pin.length<6||pin.length>32)return res.status(400).json({error:'PIN/password must be at least 6 characters.'});
 if((await q(`SELECT 1 FROM student_accounts WHERE username=$1`,[username])).rows.length)return res.status(409).json({error:'That username is already taken.'});
 const seq=await q(`SELECT nextval('el_enrollment_seq') AS seq`),enrollmentId=`SLA-${new Date().getFullYear()}-${String(Number(seq.rows[0].seq)).padStart(6,'0')}`;
 const s=newSalt(),h=hashPin(pin,s),id=uuid();
 const r=await q(`INSERT INTO student_accounts(id,username,full_name,pin_salt,pin_hash,language,enrollment_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,username,full_name,language,enrollment_id,created_at`,[id,username,fullName,s,h,language,enrollmentId]);
 await createStudentSession(res,id);await notify(id,'Welcome to SELFISH LEARNING ACADEMY','Your learning space is ready. Create a request whenever you need personalised study materials.','welcome');res.status(201).json({student:r.rows[0]});
}catch(e){next(e)}});
app.post('/api/student/login',async(req,res,next)=>{try{const username=String(req.body?.username||'').trim().toLowerCase(),pin=String(req.body?.pin||'');const r=await q(`SELECT * FROM student_accounts WHERE username=$1`,[username]);if(!r.rows.length)return res.status(401).json({error:'Invalid username or PIN/password.'});const a=r.rows[0];if(hashPin(pin,a.pin_salt)!==a.pin_hash)return res.status(401).json({error:'Invalid username or PIN/password.'});await q(`UPDATE student_accounts SET last_login_at=now() WHERE id=$1`,[a.id]);await createStudentSession(res,a.id);res.json({student:{id:a.id,username:a.username,full_name:a.full_name,language:a.language,enrollment_id:a.enrollment_id,profile_course:a.profile_course,profile_institution:a.profile_institution,photo_url:a.photo_data?'/api/student/photo':null,created_at:a.created_at}});}catch(e){next(e)}});
app.post('/api/student/logout',async(req,res,next)=>{try{await clearStudent(req,res);res.json({ok:true});}catch(e){next(e)}});
app.get('/api/student/me',async(req,res,next)=>{try{res.json({student:await student(req)});}catch(e){next(e)}});
app.get('/api/profile',async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;res.json({profile:{user_id:String(a.id),name:a.full_name,username:a.username,enrollment_id:a.enrollment_id,language:a.language,created_at:a.created_at}});}catch(e){next(e)}});

app.route('/api/requests').get(async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;const r=await q(`SELECT request_id,student_name,enrollment_id,university,programme,semester,subject,chapter,materials,notes,status,price,delivery_text,payment_ref,payment_status,access_granted,progress,created_at,updated_at FROM learning_requests WHERE user_id=$1 ORDER BY created_at DESC`,[a.id]);res.json({requests:r.rows});}catch(e){next(e)}}).post(async(req,res,next)=>{try{
 const a=await requireStudent(req,res);if(!a)return;const b=req.body||{},required=['university','programme','semester','subject','chapter'];if(required.some(k=>!String(b[k]||'').trim()))return res.status(400).json({error:'Complete all academic fields.'});const mats=Array.isArray(b.materials)?b.materials.map(String).filter(Boolean).slice(0,12):[];if(!mats.length)return res.status(400).json({error:'Choose at least one material.'});
 const s=await q(`SELECT nextval('el_request_seq') AS seq`),rid=`REQ-${String(Number(s.rows[0].seq)+1000).padStart(6,'0')}`;
 const r=await q(`INSERT INTO learning_requests(request_id,user_id,student_name,enrollment_id,university,programme,semester,subject,chapter,materials,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11) RETURNING request_id,status,created_at`,[rid,a.id,a.full_name,a.enrollment_id,String(b.university).trim(),String(b.programme).trim(),String(b.semester).trim(),String(b.subject).trim(),String(b.chapter).trim(),JSON.stringify(mats),String(b.notes||'').slice(0,2000)]);
 await q(`UPDATE student_accounts SET profile_course=COALESCE(NULLIF(profile_course,''),$1),profile_institution=COALESCE(NULLIF(profile_institution,''),$2) WHERE id=$3`,[String(b.programme).trim(),String(b.university).trim(),a.id]);await notify(a.id,'Request received',`Thank you. We received ${rid}. You will be notified here when your quotation or learning materials are ready.`,'request');res.status(201).json({request:r.rows[0],message:'Thank you. Your request has been received. You will be notified when it is ready.'});
}catch(e){next(e)}}).put(async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;const rid=String(req.body?.requestId||''),ref=String(req.body?.paymentRef||'').trim().slice(0,120);if(!rid||!ref)return res.status(400).json({error:'Request ID and payment reference are required.'});const r=await q(`UPDATE learning_requests SET payment_ref=$1,payment_status='Submitted',updated_at=now() WHERE request_id=$2 AND user_id=$3 RETURNING request_id,payment_ref,payment_status`,[ref,rid,a.id]);if(!r.rows.length)return res.status(404).json({error:'Request not found.'});await notify(a.id,'Payment reference received',`Your payment reference for ${rid} was received and is awaiting verification.`,'payment');res.json({request:r.rows[0]});}catch(e){next(e)}});

app.get('/api/materials',async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;const r=await q(`SELECT m.id,m.request_id,m.title,m.kind,m.url,m.description,m.created_at FROM learning_materials m JOIN learning_requests lr ON lr.request_id=m.request_id WHERE lr.user_id=$1 AND lr.access_granted=true ORDER BY m.created_at DESC`,[a.id]);res.json({materials:r.rows});}catch(e){next(e)}});
app.route('/api/notifications').get(async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;const r=await q(`SELECT id,title,message,type,is_read,created_at FROM student_notifications WHERE account_id=$1 ORDER BY created_at DESC LIMIT 100`,[a.id]);res.json({notifications:r.rows,unread:r.rows.filter(x=>!x.is_read).length});}catch(e){next(e)}}).put(async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;if(req.body?.all)await q(`UPDATE student_notifications SET is_read=true WHERE account_id=$1`,[a.id]);else if(req.body?.id)await q(`UPDATE student_notifications SET is_read=true WHERE id=$1::uuid AND account_id=$2`,[String(req.body.id),a.id]);res.json({ok:true});}catch(e){next(e)}});
app.route('/api/thoughts').get(async(req,res,next)=>{try{const r=await q(`SELECT id,student_name,course,thought,created_at FROM student_thoughts WHERE approved=true ORDER BY created_at DESC LIMIT 30`);res.json({thoughts:r.rows});}catch(e){next(e)}}).post(async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;const thought=String(req.body?.thought||'').trim().slice(0,500),course=String(req.body?.course||'').trim().slice(0,120);if(thought.length<12||!course)return res.status(400).json({error:'Add your course and a short thought.'});await q(`INSERT INTO student_thoughts(account_id,student_name,course,thought) VALUES($1,$2,$3,$4)`,[a.id,a.full_name,course,thought]);res.status(201).json({ok:true,message:'Thank you. Your thought will appear after review.'});}catch(e){next(e)}});

app.route('/api/student/id-card').get(async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;const r=await q(`SELECT full_name,username,enrollment_id,profile_course,profile_institution,photo_data,photo_mime FROM student_accounts WHERE id=$1`,[a.id]);const p=r.rows[0]||{},latest=(await q(`SELECT programme,university FROM learning_requests WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1`,[a.id])).rows[0]||{},course=p.profile_course||latest.programme||'',institution=p.profile_institution||latest.university||'';
 if(String(req.query?.download||'')==='1'){let avatar=`<rect x="50" y="128" width="126" height="148" rx="18" fill="#edf3e9"/><text x="113" y="213" text-anchor="middle" font-size="42" font-family="Arial" font-weight="700" fill="#146a50">${safe((p.full_name||'S')[0]?.toUpperCase())}</text>`;if(p.photo_data){const data=Buffer.from(p.photo_data).toString('base64');avatar=`<image href="data:${p.photo_mime||'image/jpeg'};base64,${data}" x="50" y="128" width="126" height="148" preserveAspectRatio="xMidYMid slice"/>`;}const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="630" viewBox="0 0 1000 630"><rect width="1000" height="630" rx="34" fill="#fbfcf8"/><rect width="1000" height="104" fill="#0b5141"/><text x="50" y="63" font-family="Arial" font-size="34" font-weight="800" fill="#fff">SELFISH LEARNING ACADEMY</text><text x="950" y="63" text-anchor="end" font-family="Arial" font-size="20" font-weight="700" fill="#e2ba56">SELFISH STUDENT</text>${avatar}<text x="210" y="158" font-family="Arial" font-size="20" fill="#65736b">STUDENT NAME</text><text x="210" y="197" font-family="Arial" font-size="34" font-weight="800" fill="#132921">${safe(p.full_name)}</text><text x="210" y="244" font-family="Arial" font-size="18" fill="#65736b">ID: ${safe(p.enrollment_id)}</text><line x1="50" y1="314" x2="950" y2="314" stroke="#dce5de"/><text x="50" y="358" font-family="Arial" font-size="18" fill="#65736b">COURSE / PROGRAMME</text><text x="50" y="393" font-family="Arial" font-size="25" font-weight="700" fill="#132921">${safe(course||'Not set')}</text><text x="50" y="447" font-family="Arial" font-size="18" fill="#65736b">UNIVERSITY / INSTITUTION</text><text x="50" y="482" font-family="Arial" font-size="23" font-weight="700" fill="#132921">${safe(institution||'Not set')}</text><rect x="50" y="525" width="900" height="66" rx="18" fill="#eef4eb"/><text x="500" y="566" text-anchor="middle" font-family="Arial" font-size="22" font-style="italic" font-weight="700" fill="#0b5141">I learn my way. I grow with SELFISH LEARNING ACADEMY.</text></svg>`;res.setHeader('Content-Type','image/svg+xml');res.setHeader('Content-Disposition',`attachment; filename="${p.enrollment_id||'SLA'}-ID-Card.svg"`);return res.send(svg);}res.json({student:{full_name:p.full_name,username:p.username,enrollment_id:p.enrollment_id,profile_course:p.profile_course,profile_institution:p.profile_institution,photo_url:p.photo_data?'/api/student/photo':null,course,institution,tagline:'I learn my way. I grow with SELFISH LEARNING ACADEMY.'}});
}catch(e){next(e)}}).put(async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;const course=String(req.body?.course||'').trim().slice(0,120),institution=String(req.body?.institution||'').trim().slice(0,160);await q(`UPDATE student_accounts SET profile_course=$1,profile_institution=$2 WHERE id=$3`,[course,institution,a.id]);res.json({student:{...a,course,institution,profile_course:course,profile_institution:institution,photo_url:a.photo_url||null,tagline:'I learn my way. I grow with SELFISH LEARNING ACADEMY.'}});}catch(e){next(e)}});
app.get('/api/student/photo',async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;const r=await q(`SELECT photo_data,photo_mime FROM student_accounts WHERE id=$1`,[a.id]);if(!r.rows[0]?.photo_data)return res.status(404).end();res.type(r.rows[0].photo_mime||'image/jpeg').send(r.rows[0].photo_data);}catch(e){next(e)}});
app.post('/api/student/photo',upload.single('photo'),async(req,res,next)=>{try{const a=await requireStudent(req,res);if(!a)return;const f=req.file;if(!f)return res.status(400).json({error:'Choose a photo first.'});if(!/^image\/(jpeg|png|webp)$/i.test(f.mimetype||''))return res.status(400).json({error:'Use JPG, PNG or WebP image.'});await q(`UPDATE student_accounts SET photo_data=$1,photo_mime=$2 WHERE id=$3`,[f.buffer,f.mimetype,a.id]);res.json({photoUrl:'/api/student/photo'});}catch(e){next(e)}});
app.post('/api/contact',async(req,res,next)=>{try{const b=req.body||{},name=String(b.name||'').trim(),email=String(b.email||'').trim().toLowerCase(),message=String(b.message||'').trim();if(name.length<2||!/^\S+@\S+\.\S+$/.test(email)||message.length<5)return res.status(400).json({error:'Enter a valid name, email and message.'});await q(`INSERT INTO contact_messages(name,email,message) VALUES($1,$2,$3)`,[name,email,message.slice(0,4000)]);res.status(201).json({ok:true});}catch(e){next(e)}});

app.get('/api/admin/auth/status',async(req,res,next)=>{try{res.json(await adminState(req));}catch(e){next(e)}});
app.post('/api/admin/auth/setup',async(req,res,next)=>{try{const code=String(req.body?.code||''),setupToken=String(req.body?.setupToken||'');if(code.length<6||code.length>64)return res.status(400).json({error:'Admin access code must be 6–64 characters.'});const cur=await q(`SELECT code_hash,setup_token_hash FROM sla_admin_security WHERE id=1`);if(cur.rows[0]?.code_hash)return res.status(409).json({error:'Admin access code is already configured.'});const expected=String(process.env.ADMIN_SETUP_TOKEN||'');if(expected&&setupToken!==expected)return res.status(403).json({error:'This is not the authorised first-time setup link.'});const s=newSalt(),h=hashAdmin(code,s);await q(`UPDATE sla_admin_security SET code_salt=$1,code_hash=$2,setup_token_hash=NULL,updated_at=now() WHERE id=1`,[s,h]);await createAdminSession(res);res.json({ok:true});}catch(e){next(e)}});
app.post('/api/admin/auth/login',async(req,res,next)=>{try{const code=String(req.body?.code||''),r=await q(`SELECT code_salt,code_hash FROM sla_admin_security WHERE id=1`),a=r.rows[0];if(!a?.code_hash)return res.status(409).json({error:'Admin access code has not been created yet.'});if(hashAdmin(code,a.code_salt)!==a.code_hash)return res.status(401).json({error:'Incorrect admin access code.'});await createAdminSession(res);res.json({ok:true});}catch(e){next(e)}});
app.post('/api/admin/auth/logout',async(req,res,next)=>{try{const raw=req.cookies?.sla_admin_session;if(raw)await q(`DELETE FROM sla_admin_sessions WHERE token_hash=$1`,[digest(raw)]);res.clearCookie('sla_admin_session',{path:'/'});res.json({ok:true});}catch(e){next(e)}});
app.route('/api/admin/requests').get(async(req,res,next)=>{try{if(!await requireAdmin(req,res))return;const r=await q(`SELECT request_id,user_id,student_name,enrollment_id,university,programme,semester,subject,chapter,materials,notes,status,price,delivery_text,payment_ref,payment_status,access_granted,progress,created_at,updated_at FROM learning_requests ORDER BY created_at DESC LIMIT 500`);res.json({requests:r.rows});}catch(e){next(e)}}).put(async(req,res,next)=>{try{if(!await requireAdmin(req,res))return;const b=req.body||{},rid=String(b.requestId||'');if(!rid)return res.status(400).json({error:'requestId required'});const prev=(await q(`SELECT user_id,status,price,delivery_text,payment_status,access_granted FROM learning_requests WHERE request_id=$1`,[rid])).rows[0];if(!prev)return res.status(404).json({error:'Request not found'});const r=await q(`UPDATE learning_requests SET status=COALESCE($1,status),price=COALESCE($2,price),delivery_text=COALESCE($3,delivery_text),payment_status=COALESCE($4,payment_status),access_granted=COALESCE($5,access_granted),progress=COALESCE($6,progress),updated_at=now() WHERE request_id=$7 RETURNING request_id,status,price,delivery_text,payment_status,access_granted,progress`,[b.status??null,b.price===''||b.price==null?null:Number(b.price),b.deliveryText??null,b.paymentStatus??null,typeof b.accessGranted==='boolean'?b.accessGranted:null,b.progress==null?null:Math.max(0,Math.min(100,Number(b.progress))),rid]);const cur=r.rows[0];let note=null;if(cur.access_granted&&!prev.access_granted)note=['Learning access granted',`Your materials for ${rid} are ready. Open your Learning Library to start.`,'ready'];else if(cur.payment_status==='Verified'&&prev.payment_status!=='Verified')note=['Payment verified',`Your payment for ${rid} has been verified. We are preparing your materials.`,'payment'];else if(cur.status!==prev.status)note=['Request updated',`${rid} status is now “${cur.status}”.`,'status'];else if((cur.price!=null&&String(cur.price)!==String(prev.price??''))||(cur.delivery_text||'')!==(prev.delivery_text||''))note=['Quotation updated',`A quotation update is available for ${rid}. Check My Requests for price and delivery details.`,'quotation'];if(note)await notify(prev.user_id,...note);res.json({request:cur});}catch(e){next(e)}});
app.route('/api/admin/materials').get(async(req,res,next)=>{try{if(!await requireAdmin(req,res))return;const r=await q(`SELECT id,request_id,title,kind,url,description,created_at FROM learning_materials ORDER BY created_at DESC LIMIT 500`);res.json({materials:r.rows});}catch(e){next(e)}}).post(async(req,res,next)=>{try{if(!await requireAdmin(req,res))return;const b=req.body||{},rid=String(b.requestId||'').trim(),title=String(b.title||'').trim(),kind=String(b.kind||'Resource').trim(),url=String(b.url||'').trim();if(!rid||!title||!/^https?:\/\//i.test(url))return res.status(400).json({error:'Valid request, title and URL required'});const r=await q(`INSERT INTO learning_materials(request_id,title,kind,url,description) VALUES($1,$2,$3,$4,$5) RETURNING id,request_id,title,kind,url,description,created_at`,[rid,title,kind,url,String(b.description||'').slice(0,1000)]);const owner=(await q(`SELECT user_id FROM learning_requests WHERE request_id=$1`,[rid])).rows[0];if(owner?.user_id)await notify(owner.user_id,'New learning material added',`${title} is now available for ${rid}. Open your Learning Library to access it.`,'material');res.status(201).json({material:r.rows[0]});}catch(e){next(e)}}).delete(async(req,res,next)=>{try{if(!await requireAdmin(req,res))return;const id=String(req.body?.id||'');if(!id)return res.status(400).json({error:'id required'});await q(`DELETE FROM learning_materials WHERE id=$1::uuid`,[id]);res.json({ok:true});}catch(e){next(e)}});
app.route('/api/admin/thoughts').get(async(req,res,next)=>{try{if(!await requireAdmin(req,res))return;const r=await q(`SELECT id,student_name,course,thought,approved,created_at FROM student_thoughts ORDER BY created_at DESC LIMIT 200`);res.json({thoughts:r.rows});}catch(e){next(e)}}).put(async(req,res,next)=>{try{if(!await requireAdmin(req,res))return;const id=String(req.body?.id||'');if(!id)return res.status(400).json({error:'id required'});await q(`UPDATE student_thoughts SET approved=$1 WHERE id=$2::uuid`,[!!req.body?.approved,id]);res.json({ok:true});}catch(e){next(e)}}).delete(async(req,res,next)=>{try{if(!await requireAdmin(req,res))return;const id=String(req.body?.id||'');if(!id)return res.status(400).json({error:'id required'});await q(`DELETE FROM student_thoughts WHERE id=$1::uuid`,[id]);res.json({ok:true});}catch(e){next(e)}});

app.use(express.static(path.join(__dirname,'public'),{maxAge:'5m'}));
app.get('*',(req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'Not found'});res.sendFile(path.join(__dirname,'public','index.html'));});
app.use((err,req,res,next)=>{console.error(err);if(res.headersSent)return next(err);res.status(500).json({error:'Server error. Please try again.'});});

ensureSchema().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`SELFISH LEARNING ACADEMY running on ${PORT}`))).catch(e=>{console.error('Database initialization failed',e);process.exit(1)});
